#!/bin/bash
set -e

readonly RM=/bin/rm
readonly SUDO=/usr/bin/sudo
readonly VCGENCMD=/usr/bin/vcgencmd
readonly AWK=/usr/bin/awk
readonly EGREP=/bin/egrep
readonly CUT=/usr/bin/cut
readonly SLEEP=/bin/sleep
readonly FILENAME=kernel_performance_data

$RM -rf $FILENAME

second=-1
$AWK -v OFS='\t' 'BEGIN { printf "%s\t%s\t%s\n", "Second elapsed", "Temperature(degrees C)", "CPU Clock(Mhz)" }'  >>$FILENAME

while true
do 
    temp=$($SUDO $VCGENCMD measure_temp | $EGREP -o '[0-9]*\.[0-9]*')
    cpu_clock=$($SUDO $VCGENCMD measure_clock arm | $CUT -d '=' -f 2-)
    second=$((second + 1))
    $AWK -v OFS='\t' -v second=''$second'' -v temp=''$temp'' -v cpu_clock=''$((cpu_clock/1000000))'' 'BEGIN { printf "%s\t%s\t%s\n", second, temp, cpu_clock }'  >>$FILENAME
    $SLEEP 1
done