#!/bin/bash
#This script controls the green LED of the Pi according to the CPU usage

# exits the script when any command fails
set -e

# specifying all excutables' paths
readonly TOP=/usr/bin/top
readonly GREP=/bin/grep
readonly CUT=/usr/bin/cut
readonly BC=/usr/bin/bc
readonly SUDO=/usr/bin/sudo
readonly TEE=/usr/bin/tee
readonly SLEEP=/bin/sleep

# if the scripts catches a "USR2" signal, it will call the reset pct led function
trap reset_pct_led USR2

reset_pct_led() {
    echo mmc0 | $SUDO $TEE /sys/class/leds/led0/trigger
    echo "exitting"
    exit
}

turn_on_pct_led() {
    echo 1 | $SUDO $TEE /sys/class/leds/led0/brightness
}

turn_off_pct_led() {
    echo 0 | $SUDO $TEE /sys/class/leds/led0/brightness
}

echo none | $SUDO $TEE /sys/class/leds/led0/trigger

while true #creates an infinite loop until the script exits itself
do 
    cpu_total=100

    cpu_idle=$($TOP -n 1 | $GREP "%Cpu(s):" | $CUT -d ',' -f 4 | $GREP -o '[0-9]*\.[0-9]*')

    cpu_usage=$(echo "$cpu_total - $cpu_idle" | $BC -l)

    led_on_time=$(echo "$cpu_usage / $cpu_total" | $BC -l)

    turn_on_pct_led

    $SLEEP "$led_on_time"

    turn_off_pct_led

    # puts the process to sleep for 1 second
    $SLEEP 1
done